### ISSUE TITLE
migration location in boot function of service provider is incorrect

### ISSUE THREAD

**Issue by garrensweet** [martinbean/laravel-menu-builder#2]
In your boot function of your Menu Service Provider, you've got the publishes directory path set to `../database/migrations/` but you don't have a `/database` directory, so the publishing fails.

``` php
$this->publishes([
            __DIR__.'/../database/migrations/' => database_path('migrations')
        ], 'migrations');
```

Should actually be:

``` php
$this->publishes([
            __DIR__.'/../migrations/' => database_path('migrations')
        ], 'migrations');
```

Thanks.

**Comment by martinbean** [comment]
@garrensweet Thanks for letting me know!
